statistics:
  fighter fight statistics: &fighter_fight_statistics
    - age
    # - notice_days
    # - body_strikes_att_opponent_per_minute
    # - body_strikes_att_per_minute
    - body_strikes_succ_opponent_per_minute
    - body_strikes_succ_per_minute
    # - clinch_strikes_att_opponent_per_minute
    # - clinch_strikes_att_per_minute
    - clinch_strikes_succ_opponent_per_minute
    - clinch_strikes_succ_per_minute
    - ctrl_time_opponent_per_minute
    - ctrl_time_per_minute
    # - distance_strikes_att_opponent_per_minute
    # - distance_strikes_att_per_minute
    - distance_strikes_succ_opponent_per_minute
    - distance_strikes_succ_per_minute
    - fighter_height_cm
    # - ground_strikes_att_opponent_per_minute
    # - ground_strikes_att_per_minute
    - ground_strikes_succ_opponent_per_minute
    - ground_strikes_succ_per_minute
    # - head_strikes_att_opponent_per_minute
    # - head_strikes_att_per_minute
    - head_strikes_succ_opponent_per_minute
    - head_strikes_succ_per_minute
    - knockdowns_opponent_per_minute
    - knockdowns_per_minute
    # - KO_opponent_per_fight
    - KO_opponent_per_minute
    - KO_per_fight
    - KO_per_minute
    # - leg_strikes_att_opponent_per_minute
    # - leg_strikes_att_per_minute
    - leg_strikes_succ_opponent_per_minute
    - leg_strikes_succ_per_minute
    - num_fight
    - reversals_opponent_per_minute
    - reversals_per_minute
    # - strikes_att_opponent_per_minute
    # - strikes_att_per_minute
    - strikes_succ_opponent_per_minute
    - strikes_succ_per_minute
    - Sub_opponent_per_fight
    - Sub_opponent_per_minute
    - Sub_per_fight
    - Sub_per_minute
    - submission_att_opponent_per_minute
    - submission_att_per_minute
    - takedown_att_opponent_per_minute
    - takedown_att_per_minute
    - takedown_succ_opponent_per_minute
    - takedown_succ_per_minute
    - time_since_last_fight
    # - total_strikes_att_opponent_per_minute
    # - total_strikes_att_per_minute
    - total_strikes_succ_opponent_per_minute
    - total_strikes_succ_per_minute
    - win_opponent_per_fight
    - win_per_fight
    - ELO
  
  previous fights statistics: &previous_fights_statistics
    - "age"
    # - "notice_days"
    # - "body_strikes_att_opponent_per_minute"
    # - "body_strikes_att_per_minute"
    - "body_strikes_succ_opponent_per_minute"
    - "body_strikes_succ_per_minute"
    # - "clinch_strikes_att_opponent_per_minute"
    # - "clinch_strikes_att_per_minute"
    - "clinch_strikes_succ_opponent_per_minute"
    - "clinch_strikes_succ_per_minute"
    - "ctrl_time_opponent_per_minute"
    - "ctrl_time_per_minute"
    # - "distance_strikes_att_opponent_per_minute"
    # - "distance_strikes_att_per_minute"
    - "distance_strikes_succ_opponent_per_minute"
    - "distance_strikes_succ_per_minute"
    # - "fighter_height_cm"
    # - "ground_strikes_att_opponent_per_minute"
    # - "ground_strikes_att_per_minute"
    - "ground_strikes_succ_opponent_per_minute"
    - "ground_strikes_succ_per_minute"
    # - "head_strikes_att_opponent_per_minute"
    # - "head_strikes_att_per_minute"
    - "head_strikes_succ_opponent_per_minute"
    - "head_strikes_succ_per_minute"
    - "knockdowns_opponent_per_minute"
    - "knockdowns_per_minute"
    # - "KO_opponent_per_fight"
    - "KO_opponent_per_minute"
    # - "KO_per_fight"
    - "KO_per_minute"
    # - "leg_strikes_att_opponent_per_minute"
    # - "leg_strikes_att_per_minute"
    - "leg_strikes_succ_opponent_per_minute"
    - "leg_strikes_succ_per_minute"
    # - "num_fight"
    # - "reversals_opponent_per_minute"
    # - "reversals_per_minute"
    # - "strikes_att_opponent_per_minute"
    # - "strikes_att_per_minute"
    - "strikes_succ_opponent_per_minute"
    - "strikes_succ_per_minute"
    # - "Sub_opponent_per_fight"
    - "Sub_opponent_per_minute"
    # - "Sub_per_fight"
    - "Sub_per_minute"
    - "submission_att_opponent_per_minute"
    - "submission_att_per_minute"
    # - "takedown_att_opponent_per_minute"
    # - "takedown_att_per_minute"
    - "takedown_succ_opponent_per_minute"
    - "takedown_succ_per_minute"
    - "time_since_last_fight" # Adding this somehow slowed the convergence and is not as good (why?) maybe because of the default value used(?) it was the mean (~ 7months)
    # "total_strikes_att_opponent_per_minute"
    # - "total_strikes_att_per_minute"
    - "total_strikes_succ_opponent_per_minute"
    - "total_strikes_succ_per_minute"
    # - "win_opponent_per_fight"
    # - "win_per_fight"
    - "ELO"
  
  fight parameters: &fight_parameters
    - num_rounds
    - weight

  previous fights parameters: &previous_fights_parameters
    - num_rounds
    - weight
    - winner

general:
  state size: &state_size 6
  mlflow tracking: False
  model filename: time_evolution_simpler.pt

data processor:
    class: DataProcessor
    args:
      data_folder: /home/cramirpe/UFC/UFCfightdata
    
    data aggregator: 
      class: WeightedDataAggregator
      args:
        alpha: -0.0001
    
    data enhancers:
      - class: SumFlexibleELO
        args:
          scaling_factor: 0
          K_factor: 30
      - class: RankedFields
        args:
          fields:
            - age
            - fighter_height_cm
          exponents:
            - 1.2
            - 1.2

filters:
  minimum fight number: 5
  minimum notice days: 60
  early split date: 2015-01-01
  split date: 2023-08-01 #2024-07-01
  max date: 2025-11-11

training:
  seed: 102
  batch size: 64
  early train epochs: 20
  train epochs: 10

dataset:
  class: DatasetWithTimeEvolution
  args:
    fighter_fight_statistics: *fighter_fight_statistics
    fight_parameters: *fight_parameters
    previous_fights_parameters: *previous_fights_parameters
    previous_fights_statistics: *previous_fights_statistics
    state_size: *state_size

forecast dataset:
  class: ForecastDatasetTimeEvolution
  args:
    fighter_fight_statistics: *fighter_fight_statistics
    fight_parameters: *fight_parameters
    previous_fights_parameters: *previous_fights_parameters
    previous_fights_statistics: *previous_fights_statistics
    state_size: *state_size


model:
  class: SimpleFightNetWithTimeEvolution
  args:
    fighter_fight_statistics: *fighter_fight_statistics
    fight_parameters: *fight_parameters
    dropout_prob: 0.45
    network_shape: [64, 32, 16,  1]
    state_size: *state_size
    fighter_transformer_kwargs:
      state_size: *state_size
      fighter_fight_statistics: *previous_fights_statistics
      fight_parameters: *previous_fights_parameters

      network_shape: [64, 32]
      dropout: 0.405

optimizer:
  class: Adam
  args:
    lr: 1.4e-3
    # weight_decay: 1.e-5
  
scheduler:
  class: ReduceLROnPlateau
  args:
    mode: min
    factor: 0.9
    patience: 5

loss:
  class: BettingLoss
  args: {}