# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        lfs: true
    - name: Pull LFS objects
      run: git lfs pull
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 coverage pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install git+https://github.com/balaustrada/ufcscraper.git
        pip install .
    - name: Test with unittest
      run: |
        python -m coverage run --source ufcpredictor -m unittest discover ufcpredictor/tests
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
            